services:
  web:
    build: .
    volumes:
      - ./staticfiles:/app/static
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/app/static
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  video_server:
    build: ./video_server
    ports:
      - "8080:80"
