# Generated by Django 5.2 on 2025-04-22 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.IntegerField(default=3)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('generado_por', models.CharField(default='arquitecto', max_length=50)),
                ('validado', models.BooleanField(default=False)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='agentes.objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=50)),
                ('prioridad', models.IntegerField(default=3)),
                ('depende_de', models.JSONField(blank=True, default=list)),
                ('actor', models.CharField(default='asistente', max_length=50)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='agentes.roadmap')),
            ],
        ),
    ]
