# Generated by Django 5.2 on 2025-04-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='checkin',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
