# Generated by Django 5.2 on 2025-04-27 00:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0002_objetivo_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivo',
            old_name='checkin',
            new_name='checkin_data',
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('objetivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='agentes.objetivo')),
            ],
        ),
    ]
